name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Build the Docker image
    - name: Build the Docker image
      run: docker build ./crypto_service --file ./crypto_service/Dockerfile --tag v1:$(date +%s)
